top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/server/mpm
builddir     = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/server/mpm
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
