top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/os/unix
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/os/unix
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
