top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

