top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/dav/fs
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/dav/fs
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/dav/fs
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
