top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/metadata
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/metadata
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/metadata

include $(top_srcdir)/build/special.mk

