top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/filters
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/filters
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/modules/filters

include $(top_srcdir)/build/special.mk

