#!/bin/sh

prefix=/home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/installed
exec_prefix=/home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/installed
exec_prefix_set=no

usage="\
Usage: pcre-config [--prefix] [--exec-prefix] [--version] [--libs] [--libs-posix] [--cflags] [--cflags-posix]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 3.9
      ;;
    --cflags | --cflags-posix)
      if test /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/installed/include != /usr/include ; then
        includes=-I/home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/installed/include
      fi
      echo $includes
      ;;
    --libs-posix)
      echo -L${prefix}/lib -lpcreposix -lpcre
      ;;
    --libs)
      echo -L${prefix}/lib -lpcre
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
