top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/metadata
builddir     = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/metadata
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/metadata

include $(top_srcdir)/build/special.mk

