top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/srclib
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/srclib
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/srclib

SUBDIRS = pcre
BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
