top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/unix
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/unix
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
