top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/echo
builddir     = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/echo
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/echo

include $(top_srcdir)/build/special.mk

