top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/http
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/http
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/http

include $(top_srcdir)/build/special.mk

