top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/os2
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/os2
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/os2

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = util_os2.c

include $(top_srcdir)/build/ltlib.mk
