top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/proxy
builddir     = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/proxy
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
