top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/os
builddir     = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/os
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
