top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/srclib
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/srclib
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
