top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/server/mpm
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/server/mpm
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
