top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/database
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/database
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/database
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
