top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/os
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/os
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
