top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/server/mpm/prefork
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/server/mpm/prefork
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
