top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/aaa
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/aaa
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/modules/aaa

include $(top_srcdir)/build/special.mk

