top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/loggers
builddir     = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/loggers
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-25520/httpd-2.0.48/modules/loggers

include $(top_srcdir)/build/special.mk

