top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/beos
builddir     = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/beos
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-21285/httpd-2.0.46/os/beos

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = os.c beosd.c

include $(top_srcdir)/build/ltlib.mk
