top_srcdir   = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
top_builddir = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9
srcdir       = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/server/mpm/prefork
builddir     = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/server/mpm/prefork
VPATH        = /home/tyu/Documents/concurrency-bugs/apache-45605/httpd-2.2.9/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
